### ISSUE TITLE
Modeling of: bibl @type="sk" w/ title @level="m" and date

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#10]
When a bibl @type="sk" contains 

- title `@level="m"`
- date
- or date in parent::bibl
- (and maybe there's an author somewhere - see Issue 9)

then create:

- F22 w/ URI from bibl @xml:id
- F24 w/ URI: [F22's URI]/published-expression
- F28_Expression_Creation w/ URI: [F22's URI]/creation
- F30_Publication_Event w/ URI: [F22's URI]/publication
- E52_Time-Span [F30's URI]/time-span

Modeling: 
F28_Expression_Creation
    R17 created
        F22_Self-contained_Expression;
    P14 carried out by
        E21_Person (if there's an author somewhere) .

F30_Publication_Event
    R24 created
        F24_Publication_Expression ;
    P4 has time-span
        E52_Time-Span . [P82a & P82b from date/text()]

F24_Publication_Expression
    P165 incorporates
        F22_Self-contained_Expression .

**Comment by csae8092** [comment]
//tei:bibl[@type="sk"][./title[@level="m"] and ./date] returns zero matches

**Comment by BOberreither** [comment]
@Level should mean @level - fixed in description.
