### ISSUE TITLE
LK labels

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#101]
# rdfs:label correction run

## listwork
- [x] All labels for F22: show only title als label (no more "Text: " or "Expression: " before title)
- [ ] Periodical-F24: [tbd]

## listperson
- [x] Currently, all person labels are missing - please re-insert them; label = pref. name value.

## legal files
- [ ] Fackel-Quotes: Text segments and passages dangling directly from the issues F22/F24 (not a text), i.e. with some kind of "0u" in the `@source` – labels look like "Text passage from:". tbd. See https://github.com/semantic-kraus/lk-data/issues/107

## legal cases
- [x]  Label currently: title of C-file, e.g. `Akte 5 Karl Kraus ca. Der Tag`; please remove "Akte \d* " before case name.

**Comment by linxOD** [comment]
> ## listwork
> * [ ]  All labels for F22: show only title als label (no more "Text: " or "Expression: " before title)
> * [ ]  Periodical-F24: [tbd]

Maybe I am looking at the wrong triples but work.trig labels have label prefixes like "Text, Expression, Issue, Periodical, ..."

**Comment by BOberreither** [comment]
@linxOD Yes, and what I mean is: They shouldn't have. For data representation in RS, we need the labels pretty 'clean', as it turns out. So please delete those prefixes in F22; for labels of other entities I'll let you know as soon as I know myself.
