### ISSUE TITLE
remove filter for fackel quotes = Umschlagseiten

### ISSUE THREAD

**Issue by linxOD** [semantic-kraus/lk-data#104]

**Comment by BOberreither** [comment]
@linxOD Seems to work nicely, just one bug: The segment-statement contains the line 
```
ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/issueIssue-not-found/published-expression> ;
```
- instead of "issueIssue-not-found", just insert the usual issue-ID (like issue787-794).
- Thanks!

**Comment by BOberreither** [comment]
@linxOD Great!
