### ISSUE TITLE
texts.trig – some missed segments

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#105]
## Segments for Textpassages Built from `//quote[matches(@source, "^#[0-9]")]`
Currently, these quote-elements occur in their `INT3_InterltextualRelationships`  and the statement of the referred-to `INT1_TextPassage`:
```
<https://sk.acdh.oeaw.ac.at/D_000001-002-000/relation/4> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb63244/passage/D_000001-002-000/4> ;
        ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/4> .
[...]
<https://sk.acdh.oeaw.ac.at/pmb63244/passage/D_000001-002-000/4> a ns1:INT1_TextPassage ;
        rdfs:label "Text passage from: [Mitteilung über angebliche Zuschrift Kraus’ an den Berliner Börsen-Kurier], in: Neues Wiener Journal, 21.11.1922"@en ;
        ns1:R10_is_Text_Passage_of sk:pmb63244 .
```
That's perfect so far. But some of these text passages need a segment linking them to their resp. published-expression. 

### Create the missing segments
The segment should look like this:
```
<https://sk.acdh.oeaw.ac.at/pmb63244/segment/D_000001-002-000/4> a ns1:INT16_Segment ;
        rdfs:label "Text segment from: [Mitteilung über angebliche Zuschrift Kraus’ an den Berliner Börsen-Kurier], in: Neues Wiener Journal, 21.11.1922"@en ;
        ns1:R16_incorporates <https://sk.acdh.oeaw.ac.at/pmb63244/passage/D_000001-002-000/4> ;
        ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/pmb63242/published-expression> .
```
#### Here are some exceptions:
- [x] Quote refers to `//bibl/bibl[@type="sk" and @subtype="standalone_text"]` – DON'T create the segment.
- [x] Quote refers to `//bibl/bibl[@type="sk" and @subtype="journal"]` – DON'T create the segment.

#### Here are some infos for the other ones:
- [x] For `//bibl/bibl[@type="sk" and @subtype="standalone_publication"]` - the ID in the URI in the last line is the same as in segment and textpassage, so in the example above it would be "pmb63244".
- [x] For `//bibl/bibl[@type="sk" and @subtype="issue"]` – Dito.
- [x] For `//bibl/bibl[@type="sk" and @subtype="article"]` – Watch out: Take the ID from the //bibl/bibl[@type="sk"]/**date/@key**. (That's the case in the example above.)

Thanks!

**Comment by BOberreither** [comment]
@linxOD Looks good, one thing, see above: "Quote refers to //bibl/bibl[@type="sk" and @subtype="standalone_text"] – DON'T create the segment."
These segments do currently exist, please create filter for `@subtype="standalone_text"` so they're not created, thanks!

(There is another issue with `@subtype="journal"`, but I'm going to fix it on the data side.

**Comment by linxOD** [comment]
@subtype="standalone_text" should be sorted out see:
https://github.com/semantic-kraus/lk-data/commit/362d63a5b188c029176cb974aacdaa523f47cb75#diff-da6978491c0fe8ae31f9fd1734de50b91b113a764594df5690e5da3af51a565aR413-R415

**Comment by BOberreither** [comment]
@linxOD Strange; maybe it's built elsewhere? This segment statement should not exist:
```
<https://sk.acdh.oeaw.ac.at/pmb57021/segment/D_000122-008-000/0> a ns1:INT16_Segment ;
        rdfs:label "Text segment from: Karl Kraus berichtigt. Zum letztenmal Kraus contra Hesse"@en ;
        ns1:R16_incorporates <https://sk.acdh.oeaw.ac.at/pmb57021/passage/D_000122-008-000/0> ;
        ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/pmb57021/published-expression> .
```
