### ISSUE TITLE
lk texts - E55_Type for E42_Identifier 

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#26]
Every Identifier needs a E55_Type. In lk texts, every Identifier seems to be an ARCHE identifier.

URI suggestion: https://sk.acdh.oeaw.ac.at/types/idno/URL/ARCHE

**Comment by csae8092** [comment]
closed with https://github.com/semantic-kraus/lk-data/commit/08d8d6caffe8c0c3fe462dd5d6cf987ef2bff21f
