### ISSUE TITLE
lk listPerson.xml: asigning new Types to persNames

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#29]
Please add an E55_Type to every E33_E41_Linguistic_Appellation (of a E21_Person) via P2_has_Type.
**Exception**: person-geburtsname-nachname (since surnames can't have a gender ...)

- If person/sex[@value="male"] add https://sk.acdh.oeaw.ac.at/types/person/persname/male
- If person/sex[@value="female"] add https://sk.acdh.oeaw.ac.at/types/person/persname/female
- If person/sex[@value="diverse"] add https://sk.acdh.oeaw.ac.at/types/person/persname/diverse

**Comment by cfhaak** [comment]
should be closed with https://github.com/acdh-oeaw/acdh-cidoc-pyutils/issues/59
(pending review)

**Comment by cfhaak** [comment]
had to reopen, since my first try to solve the problem was rejectet from beeing added to acdh_cidoc_pyutils.
