### ISSUE TITLE
occupations vs affiliations update

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#32]
In listperson (in data directory, not the one in archive), relevant affiliation elements have been changed to occupation `@type="sk"`. They contain a `@key` containing an organisation key.
For these, create:
- F51_Pursuit
- URI as usual ([person-URI]/occupation/[n])
- `rdfs:label`: [Person Name] + occupation/text()[1], e. g. "Friedell, Egon arbeitet für Nachtlicht"

Also create
- E4_Period
- URI derived from other individual-URIs, with addition: https://sk.acdh.oeaw.ac.at/ + [occupation/@key] + /period
- `rdfs:label`: "Existence of [occupation/orgName/text()]"

Modeling:
```
E21_Person p14i_performed F51_Pursuit 
[...]
. 
F51_Pursuit p10_falls_within E4_Period 
[...]
.
```
### Also: 
All affiliations are to be ignored.
Also, all temporal attributes in occupation `@type="sk"` (`@when-iso, @notBefore-iso, @notAfter-iso`) are to be ignored.

If this poses a problem for the script, these elements / attributes can be deleted.

**Comment by csae8092** [comment]
code wise fixed with https://github.com/semantic-kraus/lk-data/commit/a4cb0ab660036e7e0e270f152a284e62c346e954
ToDo: dates ranges are serialised in a stupid way out of pmb
