### ISSUE TITLE
Treating rs-, note- and quote-elements in legal docs

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#36]
(**Caution**: Please include quote-, note- and rs-Elements in the same count, so as to not create identical URIs (".../passage/1" etc.) per accident. Only include quote with some value in @source, though. Other quote-elements are to be ignored.)

# rs-Elements
## `@type="person"`
(done)

### `@subtype="legal-doc"`
refers to other legal documents in _legal kraus_
Create:
- [x] INT16_Segment, URI: `[base-URI]/xml:id/segment/[n]`
- [x] INT1_Text_Passage, URI: `[base-URI]/xml:id/passage/[n]`
- [x] INT3_Intertextual_Relationship, URI: `[base-URI]/xml:id/relation/[n]`
(Note: The [n] of all 3 of these can be the same.)
- [x] the URI of the related-to entity (which is another legal file aka an E73 that's already stated): `[base-URI]/D_.....` (from @ref)

(Note: From creating the legal document itself,
- F4_Manifestation_Singleton, URI: `[base-URI]/xml:id/carrier`
and 
- E73_Information_Object, URI: `[base-URI]/xml:id`
should already exist.)

Modeling:

- [x] F4_Manifestation_Singleton - P128_carries - INT16_Segment
- [x] F4_Manifestation_Singleton - P128_carries - E73_Information_Object
- [x] E73_Information_Object - INT:R10_has_text_passage - INT1_Text_Passage
- [x] INT16_Segment - INT:R16_incorporates - INT1_Text_Passage

- [x] **[outdated:]** INT3_Intertextual_Relationship - INT:R24_has_related_entity - INT1_Text_Passage
- [x] INT3_Intertextual_Relationship - INT:R13_has_referring_entity - INT1_Text_Passage
- [x] **[outdated:]** INT3_Intertextual_Relationship - INT:R24_has_related_entity - [related-to entity URI: '[base-URI]/D_.....` (from @ref)]
- [x] INT3_Intertextual_Relationship - INT:R12_has_referred_to_entity - [related-to entity URI: '[base-URI]/D_.....` (from @ref)]
- [x] INT3_Intertextual_Relationship rdfs:label "Intertextual Relation"@en

Like this:
```
<https://sk.acdh.oeaw.ac.at/D_000002-004-000/relation/49> a ns2:INT3_IntertextualRelationship ;
    rdfs:label "Intertextual relation"@en ;
    ns2:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/D_000002-004-000>,
    ns2:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000002-009-000/passage/49> .

```

### `@subtype="pmb"`
**Please update modeling:**
Instead of INT:R24_has_related_entity use R12 / R13:
- [x] INT3_Intertextual_Relationship - INT:R13_has_referring_entity - INT1_Text_Passage
- [x] INT3_Intertextual_Relationship - INT:R12_has_referred_to_entity - [related-to entity URI: '[base-URI]/[pmb-ID from @ref]']

Like this:
```
<https://sk.acdh.oeaw.ac.at/D_000003-005-000/relation/[n]> a ns1:INT3_IntertextualRelationship ;
    rdfs:label "Intertextual relation"@en ;
    ns2:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/0> ;
    ns2:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb63242> .
```
#### If @ref ends with ",0u1"
refers to complete issue, as far as i can see.
Create:
- The referred-to issue: URI: [base-URI]/issue[issueNr], issueNr being the 3 numbers from `@ref` preceding ",0u1"
- INT16_Segment
- INT1_Text_Passage
- INT3_Intertextual_Relationship – just like stated above.

Modeling: see above, with the referred-to-entity being the referred-to issue and the referring-entity being the text passage.

#### If @ref ends with 3 numbers
refers to either text or text passage, which can't be distinguished automatically ... so its all modeled like a reference to a whole text.
Create:
- The referred-to text: URI: [base-URI]/[textNr]

as well as
- INT16_Segment
- INT1_Text_Passage
- INT3_Intertextual_Relationship – just like stated above.

textNr: has to be looked up; [tbc]

# quote-Elements
## `starts-with(@source, "https://fackel")`
A quote from a fackel text. See https://github.com/semantic-kraus/lk-data/issues/77

## `starts-with(@source, "#D")`
A quote from another legal file.

Create:
- [x] The referred-to legal file, just the URI: [base-URI]/ID - ID being: substring-after(@source, "#")
And also, like above:
- [x] INT16_Segment (the document's F22-URI + "/segment/[n])
- [x] INT1_Text_Passage  (the document's F22-URI + "/passage/[n])
- [x] INT3_Intertextual_Relationship  (the document's F22-URI + "/relation/[n])

- [x] Modeling: see above, with the [referred-to-entity] being the referred-to legal file.
Like this:
```
<https://sk.acdh.oeaw.ac.at/D_000003-005-000/segment/0> a ns2:INT16_Segment ;
    rdfs:label "3.5 Brief Verlag Die Fackel an Der Tag"@en ;
    schema:pagination "S. 1" ;
    ns2:R16_incorporates <https://sk.acdh.oeaw.ac.at/D_000003-005-000/passage/0> ;
    ns1:P128i_is_carried_by <https://sk.acdh.oeaw.ac.at/D_000003-005-000/carrier> ;
    ns2:R41_has_location "S. 1",
        "https://id.acdh.oeaw.ac.at/legalkraus/D_000003-005-000.xml" ;
    ns2:R44_has_wording "für alles andere nur keine Berichtigung"@und .
 
<https://sk.acdh.oeaw.ac.at/D_000003-005-000/passage/0> a ns2:INT1_TextPassage ;
    rdfs:label "Text passage from: 3.5 Brief Verlag Die Fackel an Der Tag"@en ;
ns2:R44_has_wording "für alles andere nur keine Berichtigung"@und .

<https://sk.acdh.oeaw.ac.at/D_000003-005-000/relation/0> a ns2:INT3_IntertextualRelationship ;
    rdfs:label "Intertextual relation"@en ;
    ns2:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/0> ;
    ns2:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/D_000003-002-000> .
```

## `matches(@source, "^#[0-9]")`
A quote from a text in listwork.xml.

Create:
- [x] The referred-to text, just the URI: [base-URI]/ID - ID being: concat("pmb", substring-after(@source, "#"))
And also, like above:
- [x] INT16_Segment
- [x] INT1_Text_Passage
- [x] INT3_Intertextual_Relationship

- [x] Modeling: see above, with the [referred-to-entity] being the referred-to text.

## `starts-with(@source, "https://alex")` - ignore for now. 

# note-Elements - see https://github.com/semantic-kraus/lk-data/issues/76

**Comment by cfhaak** [comment]
@BOberreither I hope I solved this part correctly and checked the right boxes (not to many, I hope).  But as far as I understood, I realy just need to create something like this:
```xml
<https://sk.acdh.oeaw.ac.at/D_000001-002-000/relation/18> a ns1:INT3_IntertextualRelationship ;
    rdfs:label "Intertextual relation"@en ;
    ns1:R24_has_related_entity <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/18>,
        <https://sk.acdh.oeaw.ac.at/pmb50465> .
```

**Comment by BOberreither** [comment]
@cfhaak Changed initial issue comment to reflect slight change in data model; added examples for clarity.

**Comment by cfhaak** [comment]
Thanks, thats great! I changed it.

**Comment by cfhaak** [comment]
What I don't get: ```The referred-to legal file, just the URI: [base-URI]/ID - ID being: substring-after(@source, "#")```
Shouldn't this already exist as an E73? Do you also need the F4?

**Comment by BOberreither** [comment]
Yes, it already exists; don't create the whole statement (with the said URI as a subject); you just need is as an object in the "relation"-statement. And yes, the F4 is also needed (updated example).

**Comment by cfhaak** [comment]
still not shure, if I got everything right, but we'll see

**Comment by BOberreither** [comment]
@cfhaak - looks very good so far, thanks a lot. One minor issue (https://github.com/semantic-kraus/lk-data/issues/62).

This issue is getting cluttered; I'll make new issues for handling of:
- note-Elements
- quote[starts-with(@source, "https://fackel")]
- rs[@subtype="fackel"]
in legal docs and close this one.

Now, issue https://github.com/semantic-kraus/lk-data/issues/59 has first priority.
