### ISSUE TITLE
check if authors (listwork) are registerd in listperson

### ISSUE THREAD

**Issue by csae8092** [semantic-kraus/lk-data#47]

**Comment by cfhaak** [comment]
@BOberreither  checked this with a little script, that I just run once (so I didn't automate this …)
331 authors where found, 13 are missing: 

- pmb2823
- pmb26198
- pmb7334
- pmb10117
- pmb53330
- pmb10928
- pmb2914
- pmb10574
- pmb14049
- pmb2563
- pmb10809
- pmb13791
- pmb2150
