### ISSUE TITLE
Inverse for ns2:P12_occurred_in_the_presence_of

### ISSUE THREAD

**Issue by csae8092** [semantic-kraus/lk-data#5]
https://github.com/acdh-oeaw/acdh-cidoc-pyutils/issues/52
ns2:P12_occurred_in_the_presence_of

        should be replaced by its inverse property
        P12i_was_present_at

(wrong direction)

**Comment by BOberreither** [comment]
Problem remains:
```
E73_Information_Object ns2:P12_occurred_in_the_presence_of E5_Event
```
should be replaced by
```
E73_Information_Object ns2:P12i_was_present_at E5_Event
```
