### ISSUE TITLE
legal kraus, case files: Checking fackel-references for ambiguities

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#59]
## Step 1
Check all the note-, rs- and quote-elements inside the body-element in the xmls in legalkraus-archiv/data/editions for attributes starting with "https://fackel" and make one list for every kind: values from ```note/@*```, values from ```rs/@*```, values from ```quote/@*```.
## Step 2
Check https://github.com/semantic-kraus/fa-data/blob/main/data/indices/fackelTexts_cascaded.xml - a list of all the fackel texts.
Which of the values listed from step 1 appear in more than one @range? (Maybe create 3 .txt files for these values.)

**Comment by cfhaak** [comment]
Step1:
I searched ```lk-data/legalkraus-archiv/data/cases_tei/``` with ```//*[@*[contains("https://fackel",.)]]/normalize-space()```.
(all matches look like that: ```<idno type="URL" subtype="fackel">https://fackel.oeaw.ac.at/?p=fackelp41596</idno>```)
File contains results.
[liste.txt](https://github.com/semantic-kraus/lk-data/files/11371646/liste.txt)

**Comment by cfhaak** [comment]
These values only appear in ```@authorId```, never in ```@range```.

**Comment by BOberreither** [comment]
@cfhaak  - Hi! First of all: I think it would be enough to limit the search to the body-elements of the files. My guess is: Your xPath says ```contains("https://fackel",.)```, maybe try ```contains(., "https://fackel")```? The result should not be (limited to) references to people, we're after references to Fackel-pages.

**Comment by cfhaak** [comment]
Yes, sorry for the typo in the xpath, I posted the wrong one anyway. However: if I do a full text search for "https://fackel/" in said folder (lk-data/legalkraus-archiv/data/cases_tei/) nothing but these person-links show up. Are you shure this is the right folder? Maybe you mean the editions-folder with ```case files'```?

**Comment by BOberreither** [comment]
@cfhaak Ah, yes, I meant data/editions.

**Comment by cfhaak** [comment]
Seem like none of them is occurring more than once. Is that possible?

**Comment by cfhaak** [comment]
Its not pssible.
The links just have different cases. In the editions folder like this: "https://fackel.oeaw.ac.at/f/759,0u1" in fackelTexts_cascaded like this: "https://fackel.oeaw.ac.at/F/759,0u1". So I need to sanitize the data upfront.

**Comment by cfhaak** [comment]
The result looks like that: [results.txt](https://github.com/semantic-kraus/lk-data/files/11395615/results.txt)
The file contains per line the identitfier, ```\t```, ":", the number of occurences (if greater then 1).

**Comment by cfhaak** [comment]
[note_results.txt](https://github.com/semantic-kraus/lk-data/files/11429880/note_results.txt)
[quote_results.txt](https://github.com/semantic-kraus/lk-data/files/11429881/quote_results.txt)
[rs_results.txt](https://github.com/semantic-kraus/lk-data/files/11429883/rs_results.txt)
@BOberreither 
Here are the files as requested.
