### ISSUE TITLE
legal files: enrich listfackel.xml with ids from fackelTexts_cascaded.xml

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#66]
### Step 1: Match for every bibl in [listfackel.xml](https://github.com/semantic-kraus/lk-data/blob/main/data/indices/listfackel.xml) with fackelTexts_cascaded.xml
- ```@corresp``` with ```//@webLink```
- and biblScope: 
    - ```biblScope/@from``` with ```text/@startPage```
    - ```biblScope/@to``` with ```text/@endPage```

Now, 
- If there is more than one corresponding text-element in fackelTexts_cascaded.xml, compare listfackel.xml's ```title[@level="a"]``` with ```text/@titleText``` there. Take the one that fits better.
- If there is no corresponding text-element in fackelTexts_cascaded.xml, look if the `@corresp`-value from listfackel can be found in a `@range` in fackelTexts_cascaded.xml. If so, take that text's ID.
- If there is more than one match, take the first one in the xml-file (= high in the hierarchy).
- If `@corresp` in listfackel.xml ends with "0u1", the `@corresp` should match an issue-element in fackelTexts_cascaded.xml - take that id instead.

### Step 2 - 2 options:
1) (clean): take the ```@id``` value from the corresponding element in fackelTexts_cascaded.xml and add it to listfackel.xml - in an ```idno[@type="fackel"]/@corresp``` in the respective bibl element
2) (quick and dirty): make a key-value-list with every ```//ref/@target``` and the ```@id``` value from the corresponding element in fackelTexts_cascaded.xml

In any case: Make it so  it can be repeated when fackelTexts_cascaded.xml changes.
In any case: Also add a list of the bibl's that couldn't find a matching counterpart in fackelTexts_cascaded.xml

**Comment by cfhaak** [comment]
need to serialize to xml

**Comment by cfhaak** [comment]
Need to trigger this workflow if https://raw.githubusercontent.com/semantic-kraus/fa-data/main/data/indices/fackelTexts_cascaded.xml is changed.
