### ISSUE TITLE
renewing @key in date

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#7]
When bibl @type="sk" contains

- title @level="j" (1 or more)
- date

but does not contain

- title @level="a"
- title @level="m"

then

1. replace @key in date with parent bibl xml:id
2. replace all other identical @key with same xml:id

**Comment by csae8092** [comment]
so basically `//tei:bibl[@type="sk" and @subtype="issue"]`?

**Comment by BOberreither** [comment]
> so basically `//tei:bibl[@type="sk" and @subtype="issue"]`?

Yes. I think the attribute wasn't there yet when we started discussion on this.

**Comment by BOberreither** [comment]
Looks good.
