### ISSUE TITLE
Minor: referred-to-entity mixup

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#88]
Right now, I find this statement: 
```
<https://sk.acdh.oeaw.ac.at/D_000087-003-000/relation/7> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb41244/published-expression> ;
        ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000087-003-000/passage/7> .
```
The referring passage (last line) is created from quote from Die Fackel (`//quote[starts-with(@source, "https://fa")]`). It is an earlier `//rs[@type="work" and @subtype="pmb"]` that does actually refer to this `pmb41244/published-expression`. 
This statement also exists. It has the same referred-to-entity; here it's correct:
```
<https://sk.acdh.oeaw.ac.at/D_000087-003-000/relation/6> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb41244/published-expression> ;
        ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000087-003-000/passage/6> .
```

So I guess there is something wrong with assigning continuing numbers to the different elements?

ps.: Maybe it has something to do with this: The `@source` in the Fackel-quote is "https://fackel.oeaw.ac.at/f/757,0u4" - which, because it refers to a front page ("0u4") can not be found in the fackeltexts_cascaded in any `@range`. Maybe try filtering those out (for special treatment maybe later on)?

**Comment by linxOD** [comment]
could not verify if the filter works but fackel quotes with source that ends with "0u4" should be excluded.
