### ISSUE TITLE
All RDF data: Add Missing Inverse Triples

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#89]
## Add Missing Inverse Triples
Have a script check all the data transformed to RDF for missing triples and add them to the trig or ttl file by looking up owl:inverse properties in the sk model.
(This has to be done to all the RDF output from DW and FA as well.)

**Comment by BOberreither** [comment]
@linxOD 
## Filters for inverse triples
Output looks nice, over all; some filters need adjustment. I could only look at a few samples, this has come up so far:
- work.trig has 4061 appearances of `cidoc:P2_has_type`, work.json only 661, limited to `...types/appellation/title/main` and `/sub`
- has_title/is_title_of relations: In work.trig already most of these have their inverse relations; work.json produces all the missing ones as well as those that already exist.

So: Many missing triples are there, but some triples are redundant, others are missing. Maybe there is a limit installed somewhere in the script? And a filter option to check if the triple to be constructed is already in the data?
On the other hand: redundant triples are not a problem, only missing ones are in the end.

**Comment by linxOD** [comment]
about cidoc:p2_has_type: I think this is because there is not triple like (for idno/xml-id) in work.trig 
`<https://sk.acdh.oeaw.ac.at/types/idno/xml-id> a cidoc:E55_Type`

**Comment by BOberreither** [comment]
@linxOD Looks even better. 
Still some inverse triples missing for E55 Types without class declaration. Can we do anything in general about it, instead of producing all these "a cidoc:E55_Type" statements? Because they are about to be built elsewhere anyway, so it's kinda redundant and we have to sort through every single data set for these types (and other entities).

Anyway, here are some more E55 Types without a class declaration - ergo without inverse:
types/person/persname/female
types/person/persname/male

**Comment by BOberreither** [comment]
@linxOD 
**Here are some triples still missing in work.trig:**

Missing inverse triple for: [INT16_Segment] ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/sk_lk00485/published-expression> 
Missing inverse triple for: [F30 Publication Event] cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/pmb32624/publication/time-span> 
Missing inverse triple for: [E42 Identifier] cidoc:P1i_identifies sk:pmb29829

**Comment by BOberreither** [comment]
@linxOD 
And here some missing from texts.trig
- Missing inverse triple for: 
[INT3_IntertextualRelationship] ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/0>
- Missing inverse triple for: 
[E73_Information_Object] ns1:R10_has_Text_Passage <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/0>
- Missing inverse triple for: 
[INT16_Segment] ns1:R16_incorporates <https://sk.acdh.oeaw.ac.at/D_000001-002-000/passage/0>

**Comment by linxOD** [comment]
> https://sk.acdh.oeaw.ac.at/sk_lk00485/published-expression
namespace does not match:
owl schema: https://w3id.org/lso/intro/beta202304#R25_has_segment
work.trig: https://w3id.org/lso/intro/Vx/#R25_has_segment
same for all R* properties

regarding cidoc:P4_has_time-span https://sk.acdh.oeaw.ac.at/pmb32624/publication/time-span
I removed the filter to filter out existing inverse triples since duplicates are anyway filtered out automatically in ttl and trig

**Comment by BOberreither** [comment]
@linxOD 
Hi! I used this SPARQL to filter triples without inverse triples:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?s ?p ?o WHERE {
?p owl:inverseOf ?pi .
  graph ?g {
    ?s ?p ?o .
    FILTER NOT EXISTS { ?o ?pi ?s . }
  }
}
``` 
If you don't see any mistakes here, the results for data.trig are the following. They don't concern the inverse-triple-script, but show up as a side note.
## data.trig
### persName type male or female: some values of the element sex are "not-set", pls. make the script ignore those (assign no male/female type)
### Naked time-span
The time-span referenced in this statement does not exist anywhere else, because Miksa Rosenberg has no date element in the birth element. In these case(s), please don't just create no time-span statement (as it is now), but also eliminate the reference to it in this birth statement. (Should apply to death statements as well.)
```
<https://sk.acdh.oeaw.ac.at/pmb39166/birth> a cidoc:E67_Birth ;
        rdfs:label "Geburt von Rosenberg, Miksa"@de ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/pmb39166/birth/time-span> ;
```

**Comment by linxOD** [comment]
> @linxOD Hi! I used this SPARQL to filter triples without inverse triples:
> 
> ```
> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
> PREFIX owl: <http://www.w3.org/2002/07/owl#>
> SELECT ?s ?p ?o WHERE {
> ?p owl:inverseOf ?pi .
>   graph ?g {
>     ?s ?p ?o .
>     FILTER NOT EXISTS { ?o ?pi ?s . }
>   }
> }
> ```
> 
> If you don't see any mistakes here, the results for data.trig are the following. They don't concern the inverse-triple-script, but show up as a side note.
> 

I'm not sure where you want to apply this script. the first triple must search in the lk-general/schema.owl and the second part in one of the texts.trig.... output.

> ## data.trig
> ### persName type male or female: some values of the element sex are "not-set", pls. make the script ignore those (assign 

done!

no male/female type)
> ### Naked time-span
> The time-span referenced in this statement does not exist anywhere else, because Miksa Rosenberg has no date element in the birth element. In these case(s), please don't just create no time-span statement (as it is now), but also eliminate the reference to it in this birth statement. (Should apply to death statements as well.)
> 
> ```
> <https://sk.acdh.oeaw.ac.at/pmb39166/birth> a cidoc:E67_Birth ;
>         rdfs:label "Geburt von Rosenberg, Miksa"@de ;
>         cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/pmb39166/birth/time-span> ;
> ```

done!

> 
> ## texts.trig
> ### References to Persons
> Triples with persons as objects seem to have no inverse created; e.g., P67_refers_to, P14_carried_out_by, etc. Two guesses:
> 
> 1. This is probably because the person-statement is not part of the data, correct?
> 2. This would resolve itself if we add all data into the same big file and let the script run, correct?
> 
> ## work.trig
> Same issue as with texts.trig, looks fine otherwise.

yes, I think this should resolve itself if all data is in one file.

**Comment by BOberreither** [comment]
@linxOD 
_I'm not sure where you want to apply this script. the first triple must search in the lk-general/schema.owl and the second part in one of the texts.trig.... output._
 Yes, that's how the data is stored in my local fuseki: default graph contains .owl-data,  named graph inside default graph contains "real" data.
