### ISSUE TITLE
Modeling of: bibl @type="sk" w/ title @level="m", no date

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#9]
When a bibl @type="sk" contains:
- title @level="m"
- no date
- and there's no date in the parent::bibl as well

then create:
- F22 w. URI built from bibl @xml:id

The parent::bibl or bibl @type="sk" contains 
- author @role="hat-ubersetzt"

or
- author not(@role="hat-ubersetzt), but instead @role="hat-anonym-veroffentlicht" or @role="hat-geschaffen"

then create
- E21_Person

Modeling:
F28 Expression Creation w/ URI [F22's URI]/creation
    R17_created
        F22;
    P14_carried_out_by
        E21 Person .

**Comment by csae8092** [comment]
closed with https://github.com/semantic-kraus/lk-data/commit/8414e47bdbb2aa244150626e095f81cb2b8ca1fd
