### ISSUE TITLE
Minor (?): legal docs: treating all quotes equal

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#93]
# Treating all quotes equal

For quotes referring to Die Fackel and to other legal docs, the INT3 points at a text passage, we also build the text passage and the segment. For quotes referring to listwork.xml, we only have an INT3 which points at a whole text, not a specific text passage.
## Currently, it looks like:
```
    <https://sk.acdh.oeaw.ac.at/D_000100-001-000/relation/62> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb55033> ;
        ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000100-001-000/passage/62> .
```
We need to change the object URI in line 3 and create a Text Passage statement for it. The URI is built like in the other cases, from the values of the referring_entity:

## Desired outcome:
```
    <https://sk.acdh.oeaw.ac.at/D_000100-001-000/relation/62> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/pmb55033/passage/D_000100-001-000/62> ;
        ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/D_000100-001-000/passage/62> .

    <https://sk.acdh.oeaw.ac.at/pmb55033/passage/D_000100-001-000/62> a ns1:INT1_TextPassage ;
    rdfs:label "Text passage from: pmb55033"@en ;
    ns1:R10_is_Text_Passage_of <https://sk.acdh.oeaw.ac.at/pmb55033> .
```
(If possible, add the text title to the rdfs:label instead of the id; take title from listwork, bibl/title[1].)
Thanks!

**Comment by BOberreither** [comment]
@linxOD 
Great, two remarks: 
**1. The Text Passage looks good, except for the label:**
```
rdfs:label """Wirtschaft und Öffentliche Sicherheit. Vortrag gehalten im
            Niederösterreichischen Gewerbeverein von Polizeipräsident Schober"""@de ;
```
- Add "Text Passage from: " before title
- Change from `@de` to `@en`
- (Maybe eliminate the superfluous quotation marks?)

**2. The INT3 Intertextual Relation still looks the same**; the object in line 3 needs to change from the whole text (`sk:pmb55033`) to the text passage you've created: `<https://sk.acdh.oeaw.ac.at/pmb55033/passage/D_000100-001-000/62>`

**Comment by csae8092** [comment]
https://github.com/acdh-oeaw/acdh-cidoc-pyutils/blob/8542af486d54b309a9c6b877e3b454284295e476/acdh_cidoc_pyutils/__init__.py#L11 maybe this might help
