### ISSUE TITLE
Bits & Pieces for data.trig

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#97]
## Place Identifiers
- [x] We still have every identifier twice - any idea why?

## Place Identifiers II
- [x] There are ```@en``` language tags at rdf:value of place identifiers, please remove them.

## Other Language Issues
- [x] Birth and Death have @de, please change to @en and translate to "Birth of" / "Death of", thanks.
- [x] Many Identifiers have @und, please change to @en .

## Time-Span: Type approx 
Date elements in birth or death elements can have ```@type="approx"``` – in these cases please add a respective E55 Type. 
Time-span looks like:
```
    <https://sk.acdh.oeaw.ac.at/pmb28692/birth/time-span> a cidoc:E52_Time-Span ;
        rdfs:label "-0570"^^xsd:string ;
        cidoc:P82a_begin_of_the_begin "-0570"^^xsd:gYear ;
        cidoc:P82b_end_of_the_end "-0570"^^xsd:gYear .
```
- [x] Please add line:
`cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx> ;`

**Comment by linxOD** [comment]
https://github.com/semantic-kraus/lk-data/issues/96
