### ISSUE TITLE
data.trig: add coordinates to places

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#98]
## Adding coordinates

For every `//settlement/location`, please add one line to the E53_Place statement:
`cidoc:P168_place_is_defined_by "Point(47.37174 8.54226)"^^geo:wktLiteral`

(Note: please add namespace `http://www.opengis.net/ont/geosparql#` for "geo:".)

**Comment by BOberreither** [comment]
@linxOD 
Some seem to be missing although they have `location/geo` - data. Examples:
- pmb12083 / Hamburg-Wandsbek
- pmb1226 / Blankenese
`distinct-values(//settlement/location/geo)` in listperson has 458 results, data.trig has only 293 `cidoc:P168_place_is_defined_by`

**Comment by linxOD** [comment]
there are also some birth el with settlement duplicates e.g. person xml:id="pmb3326"
However, with the latest fix all 458 geo triples are created which is always one settlement in either birth or death
